### ISSUE TITLE
Drag and Drop not work

### ISSUE THREAD

**Issue by typo3ua** [IchHabRecht/multicolumn#23]
![multicolumns_error](https://cloud.githubusercontent.com/assets/638022/17867809/ba2ee590-68b4-11e6-9829-47e6b343a694.png)

Drag and Drop not work.

Current version TYPO3 7.6.10
Current version EXT: multicolumn 3.1.0

**Comment by IchHabRecht** [comment]
Unfortunately this is not so easy to add with the current implementation of the Drag and Drop within the TYPO3 core.

**Comment by herr-wyss** [comment]
What are the prospects for a timely implementation of a working "drag and drop" function?

**Comment by IchHabRecht** [comment]
Hi Emanuel ,

This issue is currently not on my todo list.
