### ISSUE TITLE
Tabs and Accordion don´t work...

### ISSUE THREAD

**Issue by quadronet** [IchHabRecht/multicolumn#43]
If i select effect box with or without tabs or accordion than in frontend:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method TYPO3\CMS\Core\Utility\GeneralUtility::array_merge() | Error thrown in file /html/typo3/typo3conf/ext/multicolumn/pi1/class.tx_multicolumn_pi1.php in line 232. 

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method TYPO3\CMS\Core\Utility\GeneralUtility::array_merge() \| Error thrown in file /html/typo3/typo3conf/ext/multicolumn/lib/class.tx_multicolumn_div.php in line 95
--

**Comment by mattleiser** [comment]
The array_merge () method is deprecated and removed in TYPO3 8.7.
Replace all php array_merge () with "array" + "array".

For this extension in:
hooks/class.tx_multicolumn_alt_clickmenu.php
71: $sortedItems = array_merge($sortedItems, $multicolumnMenuItems);  =>  $sortedItems = $multicolumnMenuItems + $sortedItems;

lib/class.tx_multicolumn_pi_base.php
61: $data = array_merge($data, $appendData);  =>  $data = $appendData + $data;

lib/class.tx_multicolumn_div.php
50: $config = array_merge($config, $tsConfig);  =>  $config = $tsConfig + $config;
56: $config = array_merge($config, $flexConfig);  =>  $config = $flexConfig + $config;
95: $config = GeneralUtility::array_merge($config, $flexConfig);  =>  $config = $flexConfig + $config;

pi1/class.tx_multicolumn_pi1.php
236: $listeItemsArray = \TYPO3\CMS\Core\Utility\GeneralUtility::array_merge($listeItemsArray, $this->llPrefixed);  =>  $listeItemsArray = $this->llPrefixed + $listeItemsArray;
246: $listData = \TYPO3\CMS\Core\Utility\GeneralUtility::array_merge($listData, $this->llPrefixed); =>  $listData = $this->llPrefixed + $listData;

Thanks for fixing this bug.

**Comment by IchHabRecht** [comment]
Hi @mattleiser,

Thank you for your comment. I fear you mixed up two functions here. The one coming from TYPO3 called GeneralUtility::array_merge was deprecated and removed and needs to be replaced. But the PHP array_merge function neither was deprecated nor removed and thus needs no adjustments.

Feel free to open a pull request with the change from GeneralUtility::array_merge to array_merge :-)

Thank you very much.

**Comment by IchHabRecht** [comment]
As this functionality was removed in the current version, I'm closing this ticket.
