### ISSUE TITLE
TYPO3 cut & paste and copy & paste is not working 

### ISSUE THREAD

**Issue by maltisch** [IchHabRecht/multicolumn#45]
It ist not possible to cut or copy & paste content elements into multicolumn elements in backend page view.
The content element is hidden and under multicolumn element.

TYPO3 8.7.7 and multicolumn 4.0.1
![screen shot 2017-09-27 at 20 17 32](https://user-images.githubusercontent.com/14925914/30930198-3de783cc-a3c1-11e7-8dc8-5b044f47ce7f.png)

**Comment by IchHabRecht** [comment]
Hi maltisch,

could it be that you are using the same colPos within your backend layout col that multicolumn is using? Mutlicolumn starts colPos at 10 and is increasing the position by 1 for each further column.

I guess there is some kind of interference with your backend layout configuration.

**Comment by maltisch** [comment]
Unfortunately it is a simple one column backend layout. 
![screen shot 2017-10-05 at 10 37 47](https://user-images.githubusercontent.com/14925914/31218017-4e20e154-a9b9-11e7-82b0-13efd2ca5be0.png)

![screen shot 2017-10-05 at 10 25 59](https://user-images.githubusercontent.com/14925914/31217922-e13b74b4-a9b8-11e7-880f-d3b719449828.png)

**Comment by maltisch** [comment]
It is working with TYPO3 7.6.23.
But i tried it once again on a fresh TYPO3 8.7.7 installation and i get the same problem.

**Comment by maltisch** [comment]
Oh i have used the wrong button. You have to use the same way like in TYPO3 7.6.x.
"Paste after this record" means after the whole multicolumn-element. 
<img width="893" alt="paste_after_this_record_and_dev87__typo3_cms_8_7_7_" src="https://user-images.githubusercontent.com/14925914/32725334-f0352408-c874-11e7-9248-b8f83c833f66.png">

**Comment by IchHabRecht** [comment]
I reopen this issue to have a look at this. Thanks for providing additional information!

**Comment by IchHabRecht** [comment]
Unfortunately there is no (easy) way to support the paste icons in TYPO3 8.7 within multicolumn. Therefore the assigned patch removes those icons.
