### ISSUE TITLE
ops, an error occurred!  Class 'IchHabRecht\Multicolumn\Form\FormDataProvider\TcaFlexEffectivePid' not found

### ISSUE THREAD

**Issue by ProWebs** [IchHabRecht/multicolumn#48]
After Updateing from 3.2.3 i got this error in my typo3 7.6.23 by trying to edit the siteinformation.

Downgrade to 4.0.0 works. So the bug is specific in 4.0.1

ops, an error occurred!

Class 'IchHabRecht\Multicolumn\Form\FormDataProvider\TcaFlexEffectivePid' not found

![bug](https://user-images.githubusercontent.com/16188629/31437349-46c44ae2-ae85-11e7-9b9d-7e1722b15522.jpg)

**Comment by IchHabRecht** [comment]
Hi ProWebs,

Thank you for your report. Would you mind to give me some further information about your TYPO3 installation? Are you running a composer installation? How do you update the extension? Have you tried to regenerate your autoload information (either using composer or Install Tool?

Best regards,
Nicole
