### ISSUE TITLE
update for TYPO3 9

### ISSUE THREAD

**Issue by DavidBruchmann** [IchHabRecht/multicolumn#56]
Using already the branch compatibility-9 the extension is not yet running in TYPO3 9.3.
Is there in nearer time an update to expect?
My primary concern is about content-rendering, not so much the wizards and icons

**Comment by IchHabRecht** [comment]
Hi @DavidBruchmann,

Would you mind to share the steps that you have done and the problems you have? Thank you very much,

**Comment by DavidBruchmann** [comment]
No, I don't mind ;-)

Actually the issue is that just the content (images of CE Image) is not shown.

I got the extension by git clone and checkout the compatibility-9 branch.
In the Update-wizards for TYPO3 I scanned with "Scan Extension Files" and got some issues shown, but the I just tried it.
Created CE with 2 cols including the images, included the static file and refreshed the FE without the images being shown.
That's it.
