### ISSUE TITLE
what was the reason for commit 5c4caa3 ?

### ISSUE THREAD

**Issue by DavidBruchmann** [IchHabRecht/multicolumn#64]
had removal of support for 5c4caa3 any special reason, or was  it just related to easier maintainability?

**Comment by IchHabRecht** [comment]
Hi @DavidBruchmann,

I don't think it is the task of a container extension to deliver content elements. In my opinion each user/project should define the content elements (with the js libraries) they are needing. Furthermore I don't want to support any JS libraries that I'm not aware of. Hope this helps to clarify the reasons why I decided to remove the content elements from multicolumn.

**Comment by DavidBruchmann** [comment]
Thank's Nicole, for the explanation!
