### ISSUE TITLE
Error in page module when multicolumn element is present

### ISSUE THREAD

**Issue by helmut-winkelbach** [IchHabRecht/multicolumn#65]
On TYPO3 10.4.7 with multicolumn 5.1.0

Multicolumn Main Plugin and Section Index are include in Static in TS of that page.

When opening a page with a multicolumn element present in page module, the following error occurs:

Call to undefined method TYPO3\CMS\Core\TypoScript\TemplateService::getFileName()

**Comment by IchHabRecht** [comment]
Hi @helmut-winkelbach,

I took some time to investigate into your problem. Can you confirm, that in the multicolumn container element either the option "Force equal height for each multicolumn item" or the option "Force equal height for each multicolumn column" is set? And with "When opening a page with a multicolumn element present in page module" do mean to open the frontend or backend?

**Comment by helmut-winkelbach** [comment]
Hi @IchHabRecht 
you are rignt, it was "Force equal height for each multicolumn item" in FE.

Without it this is ok.

I get Unused elements detected on this page.
![image](https://user-images.githubusercontent.com/7759015/92725474-8153ed00-f36c-11ea-932b-013a9920a728.png)

**Comment by IchHabRecht** [comment]
Hi @helmut-winkelbach,

For the "unused elements" problem please refer to #62

**Comment by IchHabRecht** [comment]
Hi @helmut-winkelbach,

The error should be gone with the newly released version 5.1.1
